insert into SHOP (SHOP_NAME, SHOP_TOWN, SHOP_ADRESS) values ('Mercedez-Benz', 'Санкт-Петербург', 'ул. Пушкина, дом Колотушкина');
insert into SHOP (SHOP_NAME, SHOP_TOWN, SHOP_ADRESS) values ('Exist.ru', 'Санкт-Петербург', 'Испытателей проспект, 39 лит А');
insert into SHOP (SHOP_NAME, SHOP_TOWN, SHOP_ADRESS) values ('PITEROILS.RU', 'Санкт-Петербург', 'Набережная Обводного канала, 115');
insert into CAR (CAR_ID, CAR_COMPANY, CAR_MODEL, CAR_PRICE, CAR_SHOP_ID) values (1, 'Mercedez', 'W205', 900000, 1);
insert into CAR (CAR_ID, CAR_COMPANY, CAR_MODEL, CAR_PRICE, CAR_SHOP_ID) values (2, 'Mercedez', 'W203', 600000, 1);
insert into CAR (CAR_ID, CAR_COMPANY, CAR_MODEL, CAR_PRICE, CAR_SHOP_ID) values (3, 'Mercedez', 'Long VI (W222, C217) Рестайлинг 350 d Long', 5400000, 1);
insert into CAR (CAR_ID, CAR_COMPANY, CAR_MODEL, CAR_PRICE, CAR_SHOP_ID) values (4, 'Mercedez', 'Long VI (W222, C217) 500 Long', 3500000, 1);
insert into CAR (CAR_ID, CAR_COMPANY, CAR_MODEL, CAR_PRICE, CAR_SHOP_ID) values (5, 'Audi', 'TT III (8S)', 2000000, 2);
insert into CAR (CAR_ID, CAR_COMPANY, CAR_MODEL, CAR_PRICE, CAR_SHOP_ID) values (6, 'Audi', 'A4 (B6)', 20000, 2);
insert into CAR (CAR_ID, CAR_COMPANY, CAR_MODEL, CAR_PRICE, CAR_SHOP_ID) values (7, 'Audi', 'e-tron I 55', 5000000, 3);
insert into CAR (CAR_ID, CAR_COMPANY, CAR_MODEL, CAR_PRICE, CAR_SHOP_ID) values (8, 'Audi', 'Q7 I (4L) Рестайлинг', 1200000, 3);
insert into CAR (CAR_ID, CAR_COMPANY, CAR_MODEL, CAR_PRICE, CAR_SHOP_ID) values (9, 'Chevrolet', 'Corvette C7 Z06', 5600000, 3);
insert into CAR (CAR_ID, CAR_COMPANY, CAR_MODEL, CAR_PRICE, CAR_SHOP_ID) values (10, 'Dodge', 'Charger VI (LD)', 2600000, 3);
insert into CAR (CAR_ID, CAR_COMPANY, CAR_MODEL, CAR_PRICE, CAR_SHOP_ID) values (11, 'Lada', 'Kalina II', 320000, 2);
insert into CUSTOMER (CUSTOMER_NAME, CUSTOMER_POSITION, CUSTOMER_SALARY, CUSTOMER_SHOP_ID) values ('Игорь', 'Младший сотрудник', 40000, 1);
insert into CUSTOMER (CUSTOMER_NAME, CUSTOMER_POSITION, CUSTOMER_SALARY, CUSTOMER_SHOP_ID) values ('Катя', 'Младший сотрудник', 40000, 1);
insert into CUSTOMER (CUSTOMER_NAME, CUSTOMER_POSITION, CUSTOMER_SALARY, CUSTOMER_SHOP_ID) values ('Валентин', 'Старший сотрудник', 80000, 1);
insert into CUSTOMER (CUSTOMER_NAME, CUSTOMER_POSITION, CUSTOMER_SALARY, CUSTOMER_SHOP_ID) values ('Черт', 'Начальник', 160000, 1);
insert into CUSTOMER (CUSTOMER_NAME, CUSTOMER_POSITION, CUSTOMER_SALARY, CUSTOMER_SHOP_ID) values ('Сергей', 'Младший сотрудник', 25000, 2);
insert into CUSTOMER (CUSTOMER_NAME, CUSTOMER_POSITION, CUSTOMER_SALARY, CUSTOMER_SHOP_ID) values ('Марина', 'Младший сотрудник', 40000, 2);
insert into CUSTOMER (CUSTOMER_NAME, CUSTOMER_POSITION, CUSTOMER_SALARY, CUSTOMER_SHOP_ID) values ('Черт еще хуже', 'Начальник', 320000, 2);